title: TensorFlow Patterns
email:
description: Collection of software patterns for TensorFlow projects.
baseurl: ""
url: ""
github_username: guildai
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
