title: TensorFlow&trade; Patterns
email:
description: Collection of software patterns for TensorFlow projects.
baseurl: ""
url: ""
github_username: guildai
markdown: kramdown
collections:
  - patterns
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
defaults:
  -
    scope:
      path: ""
    values:
      layout: page
  -
    scope:
      path: patterns
    values:
      layout: pattern
